/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPetsRouteImport } from './routes/dashboard.pets'
import { Route as DashboardNewAnalysisRouteImport } from './routes/dashboard.new-analysis'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardPetsPetIdRouteImport } from './routes/dashboard.pets.$petId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPetsRoute = DashboardPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewAnalysisRoute = DashboardNewAnalysisRouteImport.update({
  id: '/new-analysis',
  path: '/new-analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPetsPetIdRoute = DashboardPetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => DashboardPetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new-analysis': typeof DashboardNewAnalysisRoute
  '/dashboard/pets': typeof DashboardPetsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pets/$petId': typeof DashboardPetsPetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new-analysis': typeof DashboardNewAnalysisRoute
  '/dashboard/pets': typeof DashboardPetsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pets/$petId': typeof DashboardPetsPetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/new-analysis': typeof DashboardNewAnalysisRoute
  '/dashboard/pets': typeof DashboardPetsRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pets/$petId': typeof DashboardPetsPetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/history'
    | '/dashboard/new-analysis'
    | '/dashboard/pets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/pets/$petId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/history'
    | '/dashboard/new-analysis'
    | '/dashboard/pets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/pets/$petId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/admin'
    | '/dashboard/history'
    | '/dashboard/new-analysis'
    | '/dashboard/pets'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/pets/$petId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pets': {
      id: '/dashboard/pets'
      path: '/pets'
      fullPath: '/dashboard/pets'
      preLoaderRoute: typeof DashboardPetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new-analysis': {
      id: '/dashboard/new-analysis'
      path: '/new-analysis'
      fullPath: '/dashboard/new-analysis'
      preLoaderRoute: typeof DashboardNewAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pets/$petId': {
      id: '/dashboard/pets/$petId'
      path: '/$petId'
      fullPath: '/dashboard/pets/$petId'
      preLoaderRoute: typeof DashboardPetsPetIdRouteImport
      parentRoute: typeof DashboardPetsRoute
    }
  }
}

interface DashboardPetsRouteChildren {
  DashboardPetsPetIdRoute: typeof DashboardPetsPetIdRoute
}

const DashboardPetsRouteChildren: DashboardPetsRouteChildren = {
  DashboardPetsPetIdRoute: DashboardPetsPetIdRoute,
}

const DashboardPetsRouteWithChildren = DashboardPetsRoute._addFileChildren(
  DashboardPetsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardNewAnalysisRoute: typeof DashboardNewAnalysisRoute
  DashboardPetsRoute: typeof DashboardPetsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardNewAnalysisRoute: DashboardNewAnalysisRoute,
  DashboardPetsRoute: DashboardPetsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
